<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZfxCOTl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZfxCOTl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZfxCOTl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZfxCOTl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZfxCOTl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZfxCOTl',
    'container.build_id' => 'a2cbb42c',
    'container.build_time' => 1564082489,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZfxCOTl');
