<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Vtzc.JH' shared service.

return $this->privates['.service_locator.Vtzc.JH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminpartenaireController::delete' => ['privates', '.service_locator.ZgRhH2J', 'get_ServiceLocator_ZgRhH2JService.php', true],
    'App\\Controller\\AdminpartenaireController::edit' => ['privates', '.service_locator.ZgRhH2J', 'get_ServiceLocator_ZgRhH2JService.php', true],
    'App\\Controller\\AdminpartenaireController::index' => ['privates', '.service_locator.2gIWPlt', 'get_ServiceLocator_2gIWPltService.php', true],
    'App\\Controller\\AdminpartenaireController::show' => ['privates', '.service_locator.ZgRhH2J', 'get_ServiceLocator_ZgRhH2JService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\AdminpartenaireController:delete' => ['privates', '.service_locator.ZgRhH2J', 'get_ServiceLocator_ZgRhH2JService.php', true],
    'App\\Controller\\AdminpartenaireController:edit' => ['privates', '.service_locator.ZgRhH2J', 'get_ServiceLocator_ZgRhH2JService.php', true],
    'App\\Controller\\AdminpartenaireController:index' => ['privates', '.service_locator.2gIWPlt', 'get_ServiceLocator_2gIWPltService.php', true],
    'App\\Controller\\AdminpartenaireController:show' => ['privates', '.service_locator.ZgRhH2J', 'get_ServiceLocator_ZgRhH2JService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\AdminpartenaireController::delete' => '?',
    'App\\Controller\\AdminpartenaireController::edit' => '?',
    'App\\Controller\\AdminpartenaireController::index' => '?',
    'App\\Controller\\AdminpartenaireController::show' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\AdminpartenaireController:delete' => '?',
    'App\\Controller\\AdminpartenaireController:edit' => '?',
    'App\\Controller\\AdminpartenaireController:index' => '?',
    'App\\Controller\\AdminpartenaireController:show' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
